//! .envrc generation for direnv integration.

use crate::model::Service;
use std::collections::HashMap;

/// Generator for .envrc files for direnv integration.
pub struct EnvrcGenerator;

impl EnvrcGenerator {
    /// Generates a .envrc file from a list of services.
    ///
    /// # Arguments
    ///
    /// * `services` - The services to extract environment variables from
    ///
    /// # Examples
    ///
    /// ```
    /// use dtx_core::nix::EnvrcGenerator;
    /// use dtx_core::model::Service;
    ///
    /// let services = vec![
    ///     Service::new("db".to_string(), "postgres".to_string())
    ///         .with_package("postgresql".to_string()),
    /// ];
    ///
    /// let envrc = EnvrcGenerator::generate(&services);
    /// assert!(envrc.contains("use flake"));
    /// assert!(envrc.contains("PGDATA"));
    /// ```
    pub fn generate(services: &[Service]) -> String {
        let env_vars = Self::collect_env_vars(services);
        let env_exports = env_vars
            .iter()
            .map(|(k, v)| format!("export {}=\"{}\"", k, v))
            .collect::<Vec<_>>()
            .join("\n");

        let env_section = if env_exports.is_empty() {
            "# No service-specific environment variables".to_string()
        } else {
            format!("# Service-specific environment\n{}", env_exports)
        };

        format!(
            r#"# Generated by dtx - do not edit manually
# Reload with: direnv allow

use flake

# Project environment variables
export PROJECT_ROOT="$PWD"
export DATA_DIR="$PROJECT_ROOT/.data"

{}

# Ensure data directories exist
mkdir -p "$DATA_DIR/logs"
"#,
            env_section
        )
    }

    /// Generates .envrc with additional data directory setup.
    pub fn generate_with_layout(services: &[Service]) -> String {
        let base = Self::generate(services);
        let data_dirs = Self::generate_data_dirs(services);

        if data_dirs.is_empty() {
            base
        } else {
            format!(
                r#"{}
# Auto-create service data directories
{}
"#,
                base.trim_end(),
                data_dirs
            )
        }
    }

    /// Collects all environment variables from services and adds conventional ones.
    fn collect_env_vars(services: &[Service]) -> HashMap<String, String> {
        let mut vars = HashMap::new();

        for service in services {
            if !service.enabled {
                continue;
            }

            // Add user-defined environment variables
            if let Some(ref env) = service.environment {
                for (k, v) in env {
                    vars.insert(k.clone(), v.clone());
                }
            }

            // Add conventional env vars based on package
            if let Some(ref pkg) = service.package {
                match pkg.as_str() {
                    "postgresql" => {
                        vars.entry("PGDATA".to_string())
                            .or_insert("$DATA_DIR/postgres".to_string());
                        vars.entry("PGHOST".to_string())
                            .or_insert("127.0.0.1".to_string());
                        vars.entry("PGPORT".to_string()).or_insert(
                            service
                                .port
                                .map(|p| p.to_string())
                                .unwrap_or("5432".to_string()),
                        );
                    }
                    "redis" => {
                        vars.entry("REDIS_DATA".to_string())
                            .or_insert("$DATA_DIR/redis".to_string());
                    }
                    "mongodb" | "mongodb-ce" => {
                        vars.entry("MONGO_DATA".to_string())
                            .or_insert("$DATA_DIR/mongodb".to_string());
                    }
                    "mysql" | "mysql80" => {
                        vars.entry("MYSQL_DATADIR".to_string())
                            .or_insert("$DATA_DIR/mysql".to_string());
                    }
                    _ => {}
                }
            }
        }

        vars
    }

    /// Generates mkdir commands for service data directories.
    fn generate_data_dirs(services: &[Service]) -> String {
        let mut dirs: Vec<String> = services
            .iter()
            .filter(|s| s.enabled)
            .filter_map(|s| s.package.as_ref())
            .filter_map(|pkg| match pkg.as_str() {
                "postgresql" => Some("postgres"),
                "redis" => Some("redis"),
                "mongodb" | "mongodb-ce" => Some("mongodb"),
                "mysql" | "mysql80" => Some("mysql"),
                _ => None,
            })
            .map(|d| format!("mkdir -p \"$DATA_DIR/{}\"", d))
            .collect();

        // Remove duplicates
        dirs.sort();
        dirs.dedup();

        dirs.join("\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_envrc_basic() {
        let services = vec![Service::new("db".to_string(), "postgres".to_string())
            .with_package("postgresql".to_string())];

        let envrc = EnvrcGenerator::generate(&services);

        assert!(envrc.contains("use flake"));
        assert!(envrc.contains("PGDATA"));
        assert!(envrc.contains("DATA_DIR"));
        assert!(envrc.contains("PROJECT_ROOT"));
    }

    #[test]
    fn test_generate_envrc_empty() {
        let envrc = EnvrcGenerator::generate(&[]);

        assert!(envrc.contains("use flake"));
        assert!(envrc.contains("No service-specific environment variables"));
    }

    #[test]
    fn test_custom_env_vars() {
        let mut env = HashMap::new();
        env.insert("API_KEY".to_string(), "secret123".to_string());
        env.insert("DEBUG".to_string(), "true".to_string());

        let services = vec![
            Service::new("api".to_string(), "node server.js".to_string()).with_environment(env),
        ];

        let envrc = EnvrcGenerator::generate(&services);

        assert!(envrc.contains("API_KEY"));
        assert!(envrc.contains("secret123"));
        assert!(envrc.contains("DEBUG"));
    }

    #[test]
    fn test_multiple_databases() {
        let services = vec![
            Service::new("pg".to_string(), "postgres".to_string())
                .with_package("postgresql".to_string()),
            Service::new("redis".to_string(), "redis-server".to_string())
                .with_package("redis".to_string()),
        ];

        let envrc = EnvrcGenerator::generate(&services);

        assert!(envrc.contains("PGDATA"));
        assert!(envrc.contains("REDIS_DATA"));
    }

    #[test]
    fn test_generate_with_layout() {
        let services = vec![Service::new("db".to_string(), "postgres".to_string())
            .with_package("postgresql".to_string())];

        let envrc = EnvrcGenerator::generate_with_layout(&services);

        assert!(envrc.contains("use flake"));
        assert!(envrc.contains("mkdir -p"));
        assert!(envrc.contains("postgres"));
    }

    #[test]
    fn test_disabled_services_excluded() {
        let services = vec![
            Service::new("db".to_string(), "postgres".to_string())
                .with_package("postgresql".to_string()),
            Service::new("cache".to_string(), "redis".to_string())
                .with_package("redis".to_string())
                .disabled(),
        ];

        let envrc = EnvrcGenerator::generate(&services);

        assert!(envrc.contains("PGDATA"));
        assert!(!envrc.contains("REDIS_DATA"));
    }

    #[test]
    fn test_port_in_pg_env() {
        let services = vec![Service::new("db".to_string(), "postgres".to_string())
            .with_package("postgresql".to_string())
            .with_port(5433)];

        let envrc = EnvrcGenerator::generate(&services);

        assert!(envrc.contains("PGPORT=\"5433\""));
    }
}
